import { DollarProvincePrice, GoldPrice, CurrencyRate, MarketSummary, PriceHistoryPoint } from './types';

export const DEFAULT_MARKET_SUMMARY: MarketSummary = {
  cbi_official_rate: 1320,
  cbi_transfer_rate: 1310,
  baghdad_buy: 150250,
  baghdad_sell: 150500,
  baghdad_change_iqd: 250,
  baghdad_change_percent: 0.17,
  gold_ounce_usd: 2920.50,
  gold_ounce_change_usd: 5.20,
  gold_ounce_change_percent: 0.18,
  silver_ounce_usd: 32.40,
  dxy_index: 104.25,
  mithqal_21k_iqd: 515000,
  mithqal_21k_change_iqd: 1500,
  default_siyagha_fee: 10000,
  last_updated: new Date().toISOString(),
  sources: [
    'البنك المركزي العراقي (CBI)',
    'بورصة الكفاح وبورصة الحارثية',
    'سوق الصاغة والذهب في بغداد',
    'Metals.live Spot Global API'
  ]
};

export const DEFAULT_PROVINCES: DollarProvincePrice[] = [
  {
    id: 'baghdad_kifah',
    province_en: 'Baghdad (Al-Kifah)',
    province_ar: 'بغداد (بورصة الكفاح)',
    region: 'baghdad',
    market_name: 'بورصة الكفاح الرئيسية',
    buy_price: 150250,
    sell_price: 150500,
    previous_close: 150250,
    change_iqd: 250,
    change_percent: 0.17,
    high_24h: 150750,
    low_24h: 150000,
    last_updated: new Date().toISOString(),
    source: 'بورصة الكفاح المركزية',
  },
  {
    id: 'baghdad_harithiya',
    province_en: 'Baghdad (Al-Harithiya)',
    province_ar: 'بغداد (بورصة الحارثية)',
    region: 'baghdad',
    market_name: 'بورصة الحارثية',
    buy_price: 150250,
    sell_price: 150500,
    previous_close: 150250,
    change_iqd: 250,
    change_percent: 0.17,
    high_24h: 150750,
    low_24h: 150000,
    last_updated: new Date().toISOString(),
    source: 'بورصة الحارثية',
  },
  {
    id: 'erbil',
    province_en: 'Erbil',
    province_ar: 'أربيل',
    region: 'kurdistan',
    market_name: 'بورصة أربيل للصيرفة',
    buy_price: 150450,
    sell_price: 150750,
    previous_close: 150500,
    change_iqd: 250,
    change_percent: 0.17,
    high_24h: 151000,
    low_24h: 150200,
    last_updated: new Date().toISOString(),
    source: 'بورصة أربيل',
  },
  {
    id: 'sulaymaniyah',
    province_en: 'Sulaymaniyah',
    province_ar: 'السليمانية',
    region: 'kurdistan',
    market_name: 'سوق دولار السليمانية',
    buy_price: 150450,
    sell_price: 150750,
    previous_close: 150500,
    change_iqd: 250,
    change_percent: 0.17,
    high_24h: 151000,
    low_24h: 150200,
    last_updated: new Date().toISOString(),
    source: 'بورصة السليمانية',
  },
  {
    id: 'basra',
    province_en: 'Basra',
    province_ar: 'البصرة',
    region: 'south',
    market_name: 'سوق العشار للصيرفة',
    buy_price: 150400,
    sell_price: 150700,
    previous_close: 150500,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150950,
    low_24h: 150150,
    last_updated: new Date().toISOString(),
    source: 'بورصة البصرة (سوق العشار)',
  },
  {
    id: 'najaf',
    province_en: 'Najaf',
    province_ar: 'النجف الأشرف',
    region: 'middle_euphrates',
    market_name: 'سوق الصاغة والصيرفة في النجف',
    buy_price: 150300,
    sell_price: 150600,
    previous_close: 150400,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150850,
    low_24h: 150050,
    last_updated: new Date().toISOString(),
    source: 'سوق الصيرفة بالنجف',
  },
  {
    id: 'karbala',
    province_en: 'Karbala',
    province_ar: 'كربلاء المقدسة',
    region: 'middle_euphrates',
    market_name: 'بورصة كربلاء للصيرفة',
    buy_price: 150300,
    sell_price: 150600,
    previous_close: 150400,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150850,
    low_24h: 150050,
    last_updated: new Date().toISOString(),
    source: 'بورصة كربلاء',
  },
  {
    id: 'mosul',
    province_en: 'Mosul (Nineveh)',
    province_ar: 'الموصل (نينوى)',
    region: 'north',
    market_name: 'سوق النبي شيت للصيرفة',
    buy_price: 150400,
    sell_price: 150700,
    previous_close: 150500,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150950,
    low_24h: 150150,
    last_updated: new Date().toISOString(),
    source: 'بورصة الموصل',
  },
  {
    id: 'kirkuk',
    province_en: 'Kirkuk',
    province_ar: 'كركوك',
    region: 'north',
    market_name: 'سوق القلعة للصيرفة',
    buy_price: 150400,
    sell_price: 150700,
    previous_close: 150500,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150950,
    low_24h: 150150,
    last_updated: new Date().toISOString(),
    source: 'سوق الصيرفة كركوك',
  },
  {
    id: 'anbar',
    province_en: 'Anbar (Ramadi)',
    province_ar: 'الأنبار (الرمادي)',
    region: 'west',
    market_name: 'سوق الرمادي للصيرفة',
    buy_price: 150350,
    sell_price: 150650,
    previous_close: 150450,
    change_iqd: 200,
    change_percent: 0.13,
    high_24h: 150900,
    low_24h: 150100,
    last_updated: new Date().toISOString(),
    source: 'بورصة الرمادي',
  }
];

export const DEFAULT_GOLD_PRICES: GoldPrice[] = [
  {
    karat: 24,
    karat_name_ar: 'عيار 24 (الذهب الخالص / السبائك)',
    mithqal_iqd: 588500,
    mithqal_usd: 391.00,
    gram_iqd: 117700,
    gram_usd: 78.20,
    siyagha_avg_iqd: 10000,
    mithqal_with_siyagha_iqd: 598500,
    change_24h_iqd: 2000,
    change_percent: 0.34,
    last_updated: new Date().toISOString(),
    source: 'سوق الصاغة العراقي + Spot API'
  },
  {
    karat: 22,
    karat_name_ar: 'عيار 22 (الذهب الخليجي والتركي)',
    mithqal_iqd: 539500,
    mithqal_usd: 358.50,
    gram_iqd: 107900,
    gram_usd: 71.70,
    siyagha_avg_iqd: 10000,
    mithqal_with_siyagha_iqd: 549500,
    change_24h_iqd: 1800,
    change_percent: 0.34,
    last_updated: new Date().toISOString(),
    source: 'سوق الصاغة العراقي + Spot API'
  },
  {
    karat: 21,
    karat_name_ar: 'عيار 21 (الذهب العراقي الأكثر تداولاً)',
    mithqal_iqd: 515000,
    mithqal_usd: 342.50,
    gram_iqd: 103000,
    gram_usd: 68.50,
    siyagha_avg_iqd: 10000,
    mithqal_with_siyagha_iqd: 525000,
    change_24h_iqd: 1750,
    change_percent: 0.34,
    last_updated: new Date().toISOString(),
    source: 'سوق الصاغة العراقي + Spot API'
  },
  {
    karat: 18,
    karat_name_ar: 'عيار 18 (المصوغات الإيطالية الحديثة)',
    mithqal_iqd: 441500,
    mithqal_usd: 293.25,
    gram_iqd: 88300,
    gram_usd: 58.65,
    siyagha_avg_iqd: 10000,
    mithqal_with_siyagha_iqd: 451500,
    change_24h_iqd: 1500,
    change_percent: 0.34,
    last_updated: new Date().toISOString(),
    source: 'سوق الصاغة العراقي + Spot API'
  }
];

export const DEFAULT_CURRENCIES: CurrencyRate[] = [
  {
    code: 'EUR',
    name_ar: 'اليورو الأوروبي (لكل €100)',
    symbol: '€',
    flag: '🇪🇺',
    unit: 100,
    buy_iqd: 157200,
    sell_iqd: 158800,
    change_percent: 0.12,
    last_updated: new Date().toISOString()
  },
  {
    code: 'GBP',
    name_ar: 'الجنيه الإسترليني (لكل £100)',
    symbol: '£',
    flag: '🇬🇧',
    unit: 100,
    buy_iqd: 188500,
    sell_iqd: 190500,
    change_percent: -0.08,
    last_updated: new Date().toISOString()
  },
  {
    code: 'AED',
    name_ar: 'الدرهم الإماراتي (لكل 100 درهم)',
    symbol: 'د.إ',
    flag: '🇦🇪',
    unit: 100,
    buy_iqd: 40800,
    sell_iqd: 41100,
    change_percent: 0.00,
    last_updated: new Date().toISOString()
  },
  {
    code: 'SAR',
    name_ar: 'الريال السعودي (لكل 100 ريال)',
    symbol: 'ر.س',
    flag: '🇸🇦',
    unit: 100,
    buy_iqd: 39900,
    sell_iqd: 40200,
    change_percent: 0.01,
    last_updated: new Date().toISOString()
  },
  {
    code: 'TRY',
    name_ar: 'الليرة التركية (لكل 1000 ليرة)',
    symbol: '₺',
    flag: '🇹🇷',
    unit: 1000,
    buy_iqd: 42000,
    sell_iqd: 43000,
    change_percent: -0.35,
    last_updated: new Date().toISOString()
  },
  {
    code: 'JOD',
    name_ar: 'الدينار الأردني (لكل 100 دينار)',
    symbol: 'د.أ',
    flag: '🇯🇴',
    unit: 100,
    buy_iqd: 211000,
    sell_iqd: 213500,
    change_percent: 0.05,
    last_updated: new Date().toISOString()
  },
  {
    code: 'KWD',
    name_ar: 'الدينار الكويتي (لكل 100 دينار)',
    symbol: 'د.ك',
    flag: '🇰🇼',
    unit: 100,
    buy_iqd: 488000,
    sell_iqd: 493000,
    change_percent: 0.02,
    last_updated: new Date().toISOString()
  },
  {
    code: 'IRR',
    name_ar: 'التومان الإيراني (لكل 1,000,000 تومان)',
    symbol: 'تومان',
    flag: '🇮🇷',
    unit: 1000000,
    buy_iqd: 24500,
    sell_iqd: 25500,
    change_percent: -0.50,
    last_updated: new Date().toISOString()
  }
];

export const DEFAULT_HISTORY: PriceHistoryPoint[] = Array.from({ length: 30 }, (_, i) => {
  const d = new Date();
  d.setDate(d.getDate() - (29 - i));
  const baseSell = 149500 + Math.sin(i / 3) * 1000 + i * 30;
  return {
    date: `${d.getDate()}/${d.getMonth() + 1}`,
    timestamp: d.getTime(),
    baghdad_dollar_sell: Math.round(baseSell),
    baghdad_dollar_buy: Math.round(baseSell - 250),
    erbil_dollar_sell: Math.round(baseSell + 250),
    basra_dollar_sell: Math.round(baseSell + 200),
    gold_mithqal_21k: Math.round(510000 + Math.sin(i / 4) * 6000 + i * 200),
    gold_ounce_usd: Math.round((2880 + Math.sin(i / 4) * 30 + i * 1.5) * 10) / 10,
  };
});
